# Site settings
title: CareConnect
email: info@careconnect.com.au
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.careconnect.com.au" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
